name: deploy

permissions:
  contents: read

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # Install Nix
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      # Replace config.toml with prod.config.toml
      - name: Replace config.toml with prod.config.toml
        run: |
          rm -f ./config.toml
          mv ./prod.config.toml ./config.toml
      # Build
      - name: Build
        run: nix develop --command bash -c "zola build"
      # Deploy Production to Cloudflare Workers
      - name: Deploy Production to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

